### ISSUE TITLE
fix/enhancement to permit binomial parameters to be combined with row vectors

### ISSUE THREAD

**Issue by chapmandu2** [rmcelreath/rethinking#128]
I am interested in applying the measurement uncertainty approach described in chapter 14 to categorical variables rather than continuous variables.  For example in code snippet 14.5, rather than uncertainty in marriage or divorce rates, which are represented as normal distributions, I would be interested in the South variable which is coded as 0/1 depending on whether or not the state is in the south.  I tried to model this as a probability from 0-1 to represent uncertainty about whether the state was in the south or not, and then feed this into a binomial function ie:

```map2stan(
    alist(
        div_est ~ dnorm(mu, sigma),
        mu <- a + bR * south_est[i],
        div_obs ~ dnorm(div_est, div_sd),
        south_est ~ dbinom(1, south_obs),  
        a ~ dnorm(0,10),
        bR ~ dnorm(0,10),
        sigma ~ dcauchy(0,2.5)
    ) , ...
```
The problem is that the `binomial` function in stan returns an integer, and vectors in stan are always reals so you get an error:

```
No matches for: 
  vector ~ binomial(int, real[])
``` 
Trying to force the type as an int doesn't help:

```
 error in 'model8adfdbe1366_div_est___dnorm_mu__sigma_' at line 9, column 8
  -------------------------------------------------
     7: parameters{
     8:     vector[50] div_est;
     9:     int[50] south_est;
               ^
    10:     real a;
```
I think that I have to get around this by creating my own function in stan to wrap binomial and return a real rather than an integer.

If I'm going about this completely the wrong way then apologies, but I thought this could be a useful feature.

**Comment by rmcelreath** [comment]
Do you have the Experimental branch of rethinking installed? Otherwise, you won't have much luck with this approach. I think you are trying to sample a discrete parameter. Stan cannot do that.

In the Experimental branch, there are some examples of how to get around this: https://github.com/rmcelreath/rethinking/tree/Experimental#semi-automated-marginalization-for-binary-discrete-missing-values

Also see this for background: http://elevanth.org/blog/2018/01/29/algebra-and-missingness/
