### ISSUE TITLE
Trouble with binomial regression

### ISSUE THREAD

**Issue by dr-jojo** [rmcelreath/rethinking#178]
I have been working through the rethinking book fairly successfully but found some considerable confusion in chapter 10 - generalized linear models. 
The main source of my confusion comes from the chimpanzee example: p.293-p304. What is confusing me greatly is why the outcome variable is pulled_left : which side did chimp pull (1 = left, 0 = right). If that is meaningful at all depends on the counterbalancing they did prosocial_left : 1 if prosocial (1/1) option was on left. There is another variable in the data set: chose_prosoc : choice chimp made (0 = 1/0 option, 1 = 1/1 option). 
So my question is, why isn't chose_prosoc the outcome?
Couldn't you then just include condition as the predictor rather than the interaction of prosoc_left and condition? Any help on this would be much appreciated! 

Relatedly, since the model m10.3 has interactions, why aren't the variables centered or standardized? doesn't that introduce weird correlations? 

Lastly, since each row is not independent of the next (there are both blocks and different conditions) wouldn't this entire analysis be inappropriate? 

BTW - some of my confusion could be from me being a psychologist and not working with this type of data. Usually when I am doing a logistic regression, each row is a different participant that has been exposed to a treatment. 

Again, any help would be greatly appreciated!

**Comment by rmcelreath** [comment]
You could use chose_prosoc as the outcome. Since the largest effect in the data is the handedness, it will obscure that more. But you could certainly do it.

I think you will find some answers to your other questions in the later chapters.

Re centering: This is never necessary. It can help with estimation. But if you are computing posterior predictions, it doesn't matter. In the 2nd edition, I mainly talk about centering/scaling in terms of helping to establish sensible priors. You might find looking at the 2nd edition draft useful. Lots of things have changed by small amounts: https://github.com/rmcelreath/statrethinking_winter2019

**Comment by dr-jojo** [comment]
That makes sense. Since you are not as concerned with the coefficients (tide engine gears) there was little impetus to center, but if you want to present coefficients then you could center, with no difference in the posterior predictions. Thank you so much! It's really helping me make the switch to Bayesian stats.
