### ISSUE TITLE
Bug in `compare`?

### ISSUE THREAD

**Issue by emanjavacas** [rmcelreath/rethinking#231]
I am trying to compare 3 relatively simple binomial models. All are fit to the same dataset without complications. However `compare` keeps throwing this error message:

```Error in `[.data.frame`(result, , result_order): undefined columns selected```

![image](https://user-images.githubusercontent.com/6195107/81903261-cb48e400-95c1-11ea-8780-ce2de16bf640.png)

**Comment by rmcelreath** [comment]
Can you provide a complete script to repeat? None of my compare tests fail, and I've never seen this error before.

**Comment by emanjavacas** [comment]
```
library(rethinking)

df <- read.csv(unzip('100shots.zip'))
df$Dist.c <- (df$Dist - mean(df$Dist)) / sd(df$Dist)
m.d_a <- map(alist(
    Goal ~ dbinom(1, p),
    logit(p) <- a + bD * Dist * bA * A,
    a ~ dnorm(0, 2),
    c(bD, bA) ~ dnorm(0, 1)
), data=df)
m.dc_a <- map(alist(
    Goal ~ dbinom(1, p),
    logit(p) <- a + bD * Dist.c * bA * A,
    a ~ dnorm(0, 2),
    c(bD, bA) ~ dnorm(0, 1)
), data=df)
m.dXa <- map(alist(
    Goal ~ dbinom(1, p),
    logit(p) <- a + bDA * Dist.c * A,
    a ~ dnorm(0, 2),
    bDA ~ dnorm(0, 1)
), data=df)
compare(m.d_a, m.dc_a, m.dXa)
```

A screenshot with version and all.

![image](https://user-images.githubusercontent.com/6195107/81915462-e5d78900-95d2-11ea-84e2-ded33d615caf.png)


[100shots.zip](https://github.com/rmcelreath/rethinking/files/4627166/100shots.zip)

**Comment by rmcelreath** [comment]
One of the models (the first one) isn't getting a valid WAIC result. I think the linear model is malformed. Shouldn't it be:
```
logit(p) <- a + bD * Dist.c + bA * A
```
The other two linear models also have * where I assume intent is +. Multiplying bD*bA isn't identifiable. But that isn't the issue, I don't think. The issue is using Dist instead of rescaled Dist.c.

Anyway, problem is your models. Use individuals WAIC calls to debug. I will try to add a more informative error message to catch this in future.

Thanks!

**Comment by emanjavacas** [comment]
Oh, that's an embarrasing mistake :-D
Anyway, I never thought of thoroughly checking the model definition (which I should've done), but a more informative error message would have been indeed very helpful.

Thanks!
