### ISSUE TITLE
Conceptual question

### ISSUE THREAD

**Issue by dr-jojo** [rmcelreath/rethinking#251]
On page 344 of the second edition of the book there is the UC Berkeley example. Using a DAG it shows how we should condition on department. Basically he says we need to close the indirect path between department and acceptance to estimate the direct effect of gender. That all makes sense to me accept when I read one of Judea Pearls books - the book of why. On page 208 of that book Pearl talks about a situation involving a drug, blood pressure, and heart attacks. It has the same DAG. Yet in that book he says there is no back door path and therefore no need to condition on blood pressure (the mediator in that model). So stratifying the data would be bad and the aggregate would be the right answer. I am trying to understand this in the context of Simpsons paradox. I will try to attach pictures of the books. Any help here would be appreciated in terms of understanding when to condition. 

![20200625_115952](https://user-images.githubusercontent.com/53239065/85755312-d3756280-b6db-11ea-86eb-01cb3d3076b4.jpg)
![20200625_115956](https://user-images.githubusercontent.com/53239065/85755313-d4a68f80-b6db-11ea-8068-4af16494ea81.jpg)
![20200625_115943](https://user-images.githubusercontent.com/53239065/85755322-d5d7bc80-b6db-11ea-9d4b-473cca2b87b9.jpg)

**Comment by rmcelreath** [comment]
This was closed, so maybe a response is no longer wanted. I see the texts as in agreement, as the total causal effect of gender in my example is like Pearl's causal effect of the drug. But the question in my example is about only one of the paths. The lesson of my example isn't "gender doesn't influence admissions," but rather "gender doesn't directly influence admissions" (in the abstract example—I don't think we can actually say what is going on in these observational contexts, because of unmeasured confounding—there is a homework problem at the end of one of the chapters which expands on that point).

**Comment by dr-jojo** [comment]
Yup that is what I realized. The Pearl example was about the total effect and the Rethinking example was about the direct effect. Very confused at first, but thanks for the help! The Rethinking book was actually very clear to me (my favorite stats book now) but since in the example in the Pearl book it did not make it clear that total path was of interest it lead to some confusion. In this vein, I also wished he would delineate the terms "condition on" and "fixing" more clear and what that would look like in a model as some examples seem inconsistent (I am sure it is just me).
