### ISSUE TITLE
rethinking package won't install with latest rstan?

### ISSUE THREAD

**Issue by xlejx-rodsxn** [rmcelreath/rethinking#268]
Hey, im new to rstan and to the rethinking package. I cant manage to install the package from the github repository. rstan package works fine, but there seem to be some issue with the version not being compatible with the rethinking package. here is my problem:

> install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@HEAD
√  checking for file 'C:\Users\arodr\AppData\Local\Temp\Rtmpu60aRE\remotes5020fa251b\rmcelreath-rethinking-50b82ec/DESCRIPTION' ...
-  preparing 'rethinking':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'rethinking_2.12.tar.gz'
   
Installing package into ‘C:/Users/arodr/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'rethinking' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'rstan' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'rethinking'
* removing 'C:/Users/arodr/OneDrive/Documents/R/win-library/3.6/rethinking'
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) installation of package ‘C:/Users/arodr/AppData/Local/Temp/Rtmpu60aRE/file5020342151d/rethinking_2.12.tar.gz’ had non-zero exit status

it has also been noted here: https://stackoverflow.com/questions/61335299/download-r-package-via-github
without much luck.
thanks for any hints on how to solve this problem.
best,
aleja

**Comment by rmcelreath** [comment]
Do you need to update R? It should be version 4+.

**Comment by xlejx-rodsxn** [comment]
Dear Richard McElreath,
Ben Goodrich suggested in the stan forum to instead try this and it worked! but thanks for your reply and amazing book!

Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by munrosa** [comment]
I have R 4+ installed and I was having a similar issue with installing rethinking, not exactly the same error but close (see the error I had below). This suggestion from @xlejx-rodsxn helped me get the rethinking package installed -- it would be nice if this suggestion to set R_REMOTES_NO_ERRORS_FROM_WARNINGS  = TRUE was put on the main rethinking README page, because other people are probably hitting this problem, too. Thanks for the package and book @rmcelreath.

> devtools::install_github("rmcelreath/rethinking")
Downloading GitHub repo rmcelreath/rethinking@HEAD
✓  checking for file ‘/private/var/folders/sj/kc0ht5p52wzb75w0t06vy0s00000gn/T/RtmpQtl8ME/remotesf42c6a9ad690/rmcelreath-rethinking-3b48ec8/DESCRIPTION’ ...
─  preparing ‘rethinking’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘rethinking_2.13.tar.gz’ (351ms)
   
Installing package into ‘/Users/smunro/Library/R/4.0/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘rethinking’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘ggplot2’ was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package ‘rethinking’
* removing ‘/Users/smunro/Library/R/4.0/library/rethinking’
Error: Failed to install 'rethinking' from GitHub:
  (converted from warning) installation of package ‘/var/folders/sj/kc0ht5p52wzb75w0t06vy0s00000gn/T//RtmpQtl8ME/filef42c5b7cbe9d/rethinking_2.13.tar.gz’ had non-zero exit status
