### ISSUE TITLE
Matrix or arrary with 3 index

### ISSUE THREAD

**Issue by joscani** [rmcelreath/rethinking#345]
In your fantastic course I've seen this. 

```r
mGD <- ulam(
alist(
A ~ binomial(N,p),
logit(p) <- a[G,D],
matrix[G,D]:a ~ normal(0,1)
), data=dat , chains=4 , cores=4 ) 
```

And I would like to do something like that with my own data

```r 
flbi_2 <- ulam(
  alist(
    y ~ bernoulli(p),
    logit(p) <- a[gedad, sexo,prov],
    matrix[gedad,sexo, prov]:a ~ normal(0,1)
  ), data=dat , chains=4 , cores=4 , warmup = 500, iter=2000 , cmdstan=TRUE )
``` 
But I get a semantic error in stan code. Any idea? 
Thanks in advance

**Comment by rmcelreath** [comment]
You need an array instead of a matrix. With the new array syntax in the latest Stan release, I need to remake how ulam declares arrays. Sorry. But if you are willing to do it in raw Stan, it's not so complicated: https://mc-stan.org/docs/2_29/reference-manual/array-data-types.html

The trick is probably that you will need a loop over the elements in the array to assign the prior to each element. I will do some experiments when I get some time.

**Comment by joscani** [comment]
Thankd @rmcelreath

**Comment by Pezhman93** [comment]
Is this feature now added to ulam?
Can we use arrays? If yes is it possible to add an example to the tests?
Thanks.

**Comment by rmcelreath** [comment]
There is no array template. But in principle it's easy to add. I will add it to the list.

**Comment by Pezhman93** [comment]
That's great! Thanks!
