### ISSUE TITLE
dealing with interactions in sim after glimmer/map

### ISSUE THREAD

**Issue by puterleat** [rmcelreath/rethinking#36]
I really like being able to do this:

```
df1 <- data_frame(x=rnorm(100), z=rnorm(100)) %>% mutate(y=x*z+rnorm(n()))

lm1 <- glimmer(y~x+z, data=df1)
lm1.fit <- map(lm1$f, lm1$d)
sim(lm1.fit, data=expand.grid(x=-1:1, z=-1:1))
```

But I can't do this

```
lm2 <- glimmer(y~x*z, data=df1)
lm2.fit <- map(lm2$f, lm2$d)
sim(lm2.fit, data=expand.grid(x=-1:1, z=-1:1))
```

Error is "Error in eval(expr, envir, enclos) : object 'b_x_X_z' not found"

Is there a way of doing this without manually reconstructing all the interaction terms required via model matrix and regexes for replacing : with _X_?

**Comment by rmcelreath** [comment]
There are a couple of issues here.

The first is that, no, sim doesn't know how to reconstruct the interaction terms using model matrix. I haven't invested enough time in glimmer. The support tools like link and sim don't know it exists and so can't handle its foibles.

The second is that you've actually stumbled onto an interesting bug with how map objects work. Because of the glimmer naming convention, map is mistaking the interaction parameter name for a vector of parameters, due to the weird abstraction layer that I coded into it, so one can do vectors of coefficients with optim. I'll put this on the fix list.

Thanks.

**Comment by puterleat** [comment]
Ah thanks... I had actually been puzzled but he "b_" in front of the variable name, but that makes more sense. 

As feedback, I really like using glimmer as a starting point for building models and would love to see it polished so it fits together with link and sim – although I can see how much time that would take. In the shorter term if the functions for creating the dataset that glimmer uses were pulled out and made accessible then it would be nice to be able to use them manually when running sim, so this might then be possible:

```
preds <- make_data_and_munge_names_function_from_glimmer(expand.grid(x=-1:1, z=-1:1))
sim(lm2.fit, data=preds)
```
